{{- if .Values.dnsServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "multiclusterIngress.name" . | trunc 40 }}-dns-server"
  annotations:
    {{- with .Values.dnsServer.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.dnsServer.coredns.prometeheusMetricsEnabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.dnsServer.coredns.metricsPort }}"
    {{- end }}
  labels:
    {{- with .Values.dnsServer.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "multiclusterIngress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dnsServer.replicas }}
  selector:
    matchLabels:
    {{- with .Values.dnsServer.podLabels }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- include "multiclusterIngress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.dnsServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "multiclusterIngress.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.dnsServer.serviceAccount.name }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.dnsServer.podSecurityContext | nindent 8 }}
      containers:
      - name: dns-server
        args:
        - --dns-server
        env:
        - name: ListenPort
          value: "{{ .Values.dnsServer.listenPort }}"
        - name: ListenGrpcPort
          value: "{{ .Values.dnsServer.grpcPort }}"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: mcingress
        - secretRef:
            name: mcingress
        securityContext:
          {{- toYaml .Values.dnsServer.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.dnsServer.grpcPort }}
          protocol: TCP
          name: grpc
        - containerPort: {{ .Values.dnsServer.listenPort }}
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            path: /Healthz/Liveness
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /Healthz/Ready
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.dnsServer.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /app/appsettings.json
          subPath: appsettings.json
          name: appconfig
        {{ with .Values.dnsServer.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      - name: coredns
        args:
        - -conf
        - /etc/coredns/Corefile
        command:
        - /coredns
        image: "{{ .Values.dnsServer.coredns.image }}"
        imagePullPolicy: {{ .Values.dnsServer.coredns.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.dnsServer.coredns.port }}
          protocol: TCP
          name: dns-tcp
        - containerPort: {{ .Values.dnsServer.coredns.port }}
          protocol: UDP
          name: dns-udp
        - containerPort: {{ .Values.dnsServer.coredns.healthCheckPort }}
          protocol: TCP
          name: health
        - containerPort: {{ .Values.dnsServer.coredns.metricsPort }}
          protocol: TCP
          name: metrics
        - containerPort: {{ .Values.dnsServer.coredns.readinessPort }}
          protocol: TCP
          name: readiness
        resources:
          {{- toYaml .Values.dnsServer.coredns.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/coredns/Corefile
          name: coredns-config
          subPath: Corefile
        livenessProbe:
          httpGet:
            path: /health
            port: health
        readinessProbe:
          httpGet:
            path: /ready
            port: readiness
      volumes:
      - name: coredns-config
        configMap:
          name: coredns
          items:
          - key: Corefile
            path: Corefile
      - name: appconfig
        configMap:
          name: mcingress-appsettings
          items:
          - key: appsettings
            path: appsettings.json
      {{ with .Values.dnsServer.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}

      {{- with .Values.dnsServer.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 6 }}
      {{- end }}

      {{- with .Values.dnsServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.dnsServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
